package com.hr.bean;

import java.io.Serializable;

/*
    档案
 */
public class Achives implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_id
     *
     * @mbggenerated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_name
     *
     * @mbggenerated
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_sex
     *
     * @mbggenerated
     */
    private String empSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_address
     *
     * @mbggenerated
     */
    private String empAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_birth
     *
     * @mbggenerated
     */
    private String empBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_card
     *
     * @mbggenerated
     */
    private String empCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.entry_time
     *
     * @mbggenerated
     */
    private String entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_titles
     *
     * @mbggenerated
     */
    private String empTitles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.graduation_time
     *
     * @mbggenerated
     */
    private String graduationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.graduation_shcool
     *
     * @mbggenerated
     */
    private String graduationShcool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.education
     *
     * @mbggenerated
     */
    private Integer education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_depart
     *
     * @mbggenerated
     */
    private Integer empDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.emp_status
     *
     * @mbggenerated
     */
    private Integer empStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.ext_a
     *
     * @mbggenerated
     */
    private String extA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.ext_b
     *
     * @mbggenerated
     */
    private String extB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achives.ext_c
     *
     * @mbggenerated
     */
    private String extC;

    
    private String departName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table achives
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_id
     *
     * @return the value of achives.emp_id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_id
     *
     * @param empId the value for achives.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_name
     *
     * @return the value of achives.emp_name
     *
     * @mbggenerated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_name
     *
     * @param empName the value for achives.emp_name
     *
     * @mbggenerated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_sex
     *
     * @return the value of achives.emp_sex
     *
     * @mbggenerated
     */
    public String getEmpSex() {
        return empSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_sex
     *
     * @param empSex the value for achives.emp_sex
     *
     * @mbggenerated
     */
    public void setEmpSex(String empSex) {
        this.empSex = empSex == null ? null : empSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_address
     *
     * @return the value of achives.emp_address
     *
     * @mbggenerated
     */
    public String getEmpAddress() {
        return empAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_address
     *
     * @param empAddress the value for achives.emp_address
     *
     * @mbggenerated
     */
    public void setEmpAddress(String empAddress) {
        this.empAddress = empAddress == null ? null : empAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_birth
     *
     * @return the value of achives.emp_birth
     *
     * @mbggenerated
     */
    public String getEmpBirth() {
        return empBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_birth
     *
     * @param empBirth the value for achives.emp_birth
     *
     * @mbggenerated
     */
    public void setEmpBirth(String empBirth) {
        this.empBirth = empBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_card
     *
     * @return the value of achives.emp_card
     *
     * @mbggenerated
     */
    public String getEmpCard() {
        return empCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_card
     *
     * @param empCard the value for achives.emp_card
     *
     * @mbggenerated
     */
    public void setEmpCard(String empCard) {
        this.empCard = empCard == null ? null : empCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.entry_time
     *
     * @return the value of achives.entry_time
     *
     * @mbggenerated
     */
    public String getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.entry_time
     *
     * @param entryTime the value for achives.entry_time
     *
     * @mbggenerated
     */
    public void setEntryTime(String entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_titles
     *
     * @return the value of achives.emp_titles
     *
     * @mbggenerated
     */
    public String getEmpTitles() {
        return empTitles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_titles
     *
     * @param empTitles the value for achives.emp_titles
     *
     * @mbggenerated
     */
    public void setEmpTitles(String empTitles) {
        this.empTitles = empTitles == null ? null : empTitles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.mobile
     *
     * @return the value of achives.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.mobile
     *
     * @param mobile the value for achives.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.graduation_time
     *
     * @return the value of achives.graduation_time
     *
     * @mbggenerated
     */
    public String getGraduationTime() {
        return graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.graduation_time
     *
     * @param graduationTime the value for achives.graduation_time
     *
     * @mbggenerated
     */
    public void setGraduationTime(String graduationTime) {
        this.graduationTime = graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.graduation_shcool
     *
     * @return the value of achives.graduation_shcool
     *
     * @mbggenerated
     */
    public String getGraduationShcool() {
        return graduationShcool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.graduation_shcool
     *
     * @param graduationShcool the value for achives.graduation_shcool
     *
     * @mbggenerated
     */
    public void setGraduationShcool(String graduationShcool) {
        this.graduationShcool = graduationShcool == null ? null : graduationShcool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.education
     *
     * @return the value of achives.education
     *
     * @mbggenerated
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.education
     *
     * @param education the value for achives.education
     *
     * @mbggenerated
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_depart
     *
     * @return the value of achives.emp_depart
     *
     * @mbggenerated
     */
    public Integer getEmpDepart() {
        return empDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_depart
     *
     * @param empDepart the value for achives.emp_depart
     *
     * @mbggenerated
     */
    public void setEmpDepart(Integer empDepart) {
        this.empDepart = empDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.emp_status
     *
     * @return the value of achives.emp_status
     *
     * @mbggenerated
     */
    public Integer getEmpStatus() {
        return empStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.emp_status
     *
     * @param empStatus the value for achives.emp_status
     *
     * @mbggenerated
     */
    public void setEmpStatus(Integer empStatus) {
        this.empStatus = empStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.ext_a
     *
     * @return the value of achives.ext_a
     *
     * @mbggenerated
     */
    public String getExtA() {
        return extA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.ext_a
     *
     * @param extA the value for achives.ext_a
     *
     * @mbggenerated
     */
    public void setExtA(String extA) {
        this.extA = extA == null ? null : extA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.ext_b
     *
     * @return the value of achives.ext_b
     *
     * @mbggenerated
     */
    public String getExtB() {
        return extB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.ext_b
     *
     * @param extB the value for achives.ext_b
     *
     * @mbggenerated
     */
    public void setExtB(String extB) {
        this.extB = extB == null ? null : extB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achives.ext_c
     *
     * @return the value of achives.ext_c
     *
     * @mbggenerated
     */
    public String getExtC() {
        return extC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achives.ext_c
     *
     * @param extC the value for achives.ext_c
     *
     * @mbggenerated
     */
    public void setExtC(String extC) {
        this.extC = extC == null ? null : extC.trim();
    }

	public String getDepartName() {
		return departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	@Override
	public String toString() {
		return "Achives [empId=" + empId + ", empName=" + empName + ", empSex=" + empSex + ", empAddress=" + empAddress
				+ ", empBirth=" + empBirth + ", empCard=" + empCard + ", entryTime=" + entryTime + ", empTitles="
				+ empTitles + ", mobile=" + mobile + ", graduationTime=" + graduationTime + ", graduationShcool="
				+ graduationShcool + ", education=" + education + ", empDepart=" + empDepart + ", empStatus="
				+ empStatus + ", extA=" + extA + ", extB=" + extB + ", extC=" + extC + ", departName=" + departName
				+ "]";
	}
    
}