package com.hr.bean;

import java.io.Serializable;

public class Depart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.depart_id
     *
     * @mbggenerated
     */
    private Integer departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.depart_name
     *
     * @mbggenerated
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.depart_status
     *
     * @mbggenerated
     */
    private Integer departStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.ext_a
     *
     * @mbggenerated
     */
    private String extA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.ext_b
     *
     * @mbggenerated
     */
    private String extB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.ext_c
     *
     * @mbggenerated
     */
    private String extC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table depart
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.depart_id
     *
     * @return the value of depart.depart_id
     *
     * @mbggenerated
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.depart_id
     *
     * @param departId the value for depart.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.depart_name
     *
     * @return the value of depart.depart_name
     *
     * @mbggenerated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.depart_name
     *
     * @param departName the value for depart.depart_name
     *
     * @mbggenerated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.depart_status
     *
     * @return the value of depart.depart_status
     *
     * @mbggenerated
     */
    public Integer getDepartStatus() {
        return departStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.depart_status
     *
     * @param departStatus the value for depart.depart_status
     *
     * @mbggenerated
     */
    public void setDepartStatus(Integer departStatus) {
        this.departStatus = departStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.create_time
     *
     * @return the value of depart.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.create_time
     *
     * @param createTime the value for depart.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.ext_a
     *
     * @return the value of depart.ext_a
     *
     * @mbggenerated
     */
    public String getExtA() {
        return extA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.ext_a
     *
     * @param extA the value for depart.ext_a
     *
     * @mbggenerated
     */
    public void setExtA(String extA) {
        this.extA = extA == null ? null : extA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.ext_b
     *
     * @return the value of depart.ext_b
     *
     * @mbggenerated
     */
    public String getExtB() {
        return extB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.ext_b
     *
     * @param extB the value for depart.ext_b
     *
     * @mbggenerated
     */
    public void setExtB(String extB) {
        this.extB = extB == null ? null : extB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.ext_c
     *
     * @return the value of depart.ext_c
     *
     * @mbggenerated
     */
    public String getExtC() {
        return extC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.ext_c
     *
     * @param extC the value for depart.ext_c
     *
     * @mbggenerated
     */
    public void setExtC(String extC) {
        this.extC = extC == null ? null : extC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", departId=").append(departId);
        sb.append(", departName=").append(departName);
        sb.append(", departStatus=").append(departStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", extA=").append(extA);
        sb.append(", extB=").append(extB);
        sb.append(", extC=").append(extC);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}