package com.hr.bean;

import java.io.Serializable;

/*
    面试
 */
public class Recruit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruit_id
     *
     * @mbggenerated
     */
    private Integer recruitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.person_sex
     *
     * @mbggenerated
     */
    private Integer personSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruit_date
     *
     * @mbggenerated
     */
    private String recruitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.graduation_school
     *
     * @mbggenerated
     */
    private String graduationSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.graduation_date
     *
     * @mbggenerated
     */
    private String graduationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.education
     *
     * @mbggenerated
     */
    private Integer education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruit_result
     *
     * @mbggenerated
     */
    private Integer recruitResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruit_status
     *
     * @mbggenerated
     */
    private Integer recruitStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.ext_a
     *
     * @mbggenerated
     */
    private String extA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.ext_b
     *
     * @mbggenerated
     */
    private String extB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.ext_c
     *
     * @mbggenerated
     */
    private String extC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recruit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruit_id
     *
     * @return the value of recruit.recruit_id
     *
     * @mbggenerated
     */
    public Integer getRecruitId() {
        return recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruit_id
     *
     * @param recruitId the value for recruit.recruit_id
     *
     * @mbggenerated
     */
    public void setRecruitId(Integer recruitId) {
        this.recruitId = recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.person_name
     *
     * @return the value of recruit.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.person_name
     *
     * @param personName the value for recruit.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.person_sex
     *
     * @return the value of recruit.person_sex
     *
     * @mbggenerated
     */
    public Integer getPersonSex() {
        return personSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.person_sex
     *
     * @param personSex the value for recruit.person_sex
     *
     * @mbggenerated
     */
    public void setPersonSex(Integer personSex) {
        this.personSex = personSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruit_date
     *
     * @return the value of recruit.recruit_date
     *
     * @mbggenerated
     */
    public String getRecruitDate() {
        return recruitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruit_date
     *
     * @param recruitDate the value for recruit.recruit_date
     *
     * @mbggenerated
     */
    public void setRecruitDate(String recruitDate) {
        this.recruitDate = recruitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.graduation_school
     *
     * @return the value of recruit.graduation_school
     *
     * @mbggenerated
     */
    public String getGraduationSchool() {
        return graduationSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.graduation_school
     *
     * @param graduationSchool the value for recruit.graduation_school
     *
     * @mbggenerated
     */
    public void setGraduationSchool(String graduationSchool) {
        this.graduationSchool = graduationSchool == null ? null : graduationSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.graduation_date
     *
     * @return the value of recruit.graduation_date
     *
     * @mbggenerated
     */
    public String getGraduationDate() {
        return graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.graduation_date
     *
     * @param graduationDate the value for recruit.graduation_date
     *
     * @mbggenerated
     */
    public void setGraduationDate(String graduationDate) {
        this.graduationDate = graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.education
     *
     * @return the value of recruit.education
     *
     * @mbggenerated
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.education
     *
     * @param education the value for recruit.education
     *
     * @mbggenerated
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruit_result
     *
     * @return the value of recruit.recruit_result
     *
     * @mbggenerated
     */
    public Integer getRecruitResult() {
        return recruitResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruit_result
     *
     * @param recruitResult the value for recruit.recruit_result
     *
     * @mbggenerated
     */
    public void setRecruitResult(Integer recruitResult) {
        this.recruitResult = recruitResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruit_status
     *
     * @return the value of recruit.recruit_status
     *
     * @mbggenerated
     */
    public Integer getRecruitStatus() {
        return recruitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruit_status
     *
     * @param recruitStatus the value for recruit.recruit_status
     *
     * @mbggenerated
     */
    public void setRecruitStatus(Integer recruitStatus) {
        this.recruitStatus = recruitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.ext_a
     *
     * @return the value of recruit.ext_a
     *
     * @mbggenerated
     */
    public String getExtA() {
        return extA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.ext_a
     *
     * @param extA the value for recruit.ext_a
     *
     * @mbggenerated
     */
    public void setExtA(String extA) {
        this.extA = extA == null ? null : extA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.ext_b
     *
     * @return the value of recruit.ext_b
     *
     * @mbggenerated
     */
    public String getExtB() {
        return extB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.ext_b
     *
     * @param extB the value for recruit.ext_b
     *
     * @mbggenerated
     */
    public void setExtB(String extB) {
        this.extB = extB == null ? null : extB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.ext_c
     *
     * @return the value of recruit.ext_c
     *
     * @mbggenerated
     */
    public String getExtC() {
        return extC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.ext_c
     *
     * @param extC the value for recruit.ext_c
     *
     * @mbggenerated
     */
    public void setExtC(String extC) {
        this.extC = extC == null ? null : extC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recruitId=").append(recruitId);
        sb.append(", personName=").append(personName);
        sb.append(", personSex=").append(personSex);
        sb.append(", recruitDate=").append(recruitDate);
        sb.append(", graduationSchool=").append(graduationSchool);
        sb.append(", graduationDate=").append(graduationDate);
        sb.append(", education=").append(education);
        sb.append(", recruitResult=").append(recruitResult);
        sb.append(", recruitStatus=").append(recruitStatus);
        sb.append(", extA=").append(extA);
        sb.append(", extB=").append(extB);
        sb.append(", extC=").append(extC);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}