package com.hr.bean;

import java.io.Serializable;
public class Salary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.salary_id
     *
     * @mbggenerated
     */
    private Integer salaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.emp_id
     *
     * @mbggenerated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.base_salary
     *
     * @mbggenerated
     */
    private Double baseSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.achievements
     *
     * @mbggenerated
     */
    private Double achievements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.bonus
     *
     * @mbggenerated
     */
    private Double bonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.check_deduction
     *
     * @mbggenerated
     */
    private Double checkDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.sum_salary
     *
     * @mbggenerated
     */
    private Double sumSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.salary_month
     *
     * @mbggenerated
     */
    private String salaryMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.salary_status
     *
     * @mbggenerated
     */
    private Integer salaryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.ext_a
     *
     * @mbggenerated
     */
    private String extA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.ext_b
     *
     * @mbggenerated
     */
    private String extB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.ext_c
     *
     * @mbggenerated
     */
    private String extC;
    
    
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.salary_id
     *
     * @return the value of salary.salary_id
     *
     * @mbggenerated
     */
    public Integer getSalaryId() {
        return salaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.salary_id
     *
     * @param salaryId the value for salary.salary_id
     *
     * @mbggenerated
     */
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.emp_id
     *
     * @return the value of salary.emp_id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.emp_id
     *
     * @param empId the value for salary.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.base_salary
     *
     * @return the value of salary.base_salary
     *
     * @mbggenerated
     */
    public Double getBaseSalary() {
        return baseSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.base_salary
     *
     * @param baseSalary the value for salary.base_salary
     *
     * @mbggenerated
     */
    public void setBaseSalary(Double baseSalary) {
        this.baseSalary = baseSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.achievements
     *
     * @return the value of salary.achievements
     *
     * @mbggenerated
     */
    public Double getAchievements() {
        return achievements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.achievements
     *
     * @param achievements the value for salary.achievements
     *
     * @mbggenerated
     */
    public void setAchievements(Double achievements) {
        this.achievements = achievements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.bonus
     *
     * @return the value of salary.bonus
     *
     * @mbggenerated
     */
    public Double getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.bonus
     *
     * @param bonus the value for salary.bonus
     *
     * @mbggenerated
     */
    public void setBonus(Double bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.check_deduction
     *
     * @return the value of salary.check_deduction
     *
     * @mbggenerated
     */
    public Double getCheckDeduction() {
        return checkDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.check_deduction
     *
     * @param checkDeduction the value for salary.check_deduction
     *
     * @mbggenerated
     */
    public void setCheckDeduction(Double checkDeduction) {
        this.checkDeduction = checkDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.sum_salary
     *
     * @return the value of salary.sum_salary
     *
     * @mbggenerated
     */
    public Double getSumSalary() {
        return sumSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.sum_salary
     *
     * @param sumSalary the value for salary.sum_salary
     *
     * @mbggenerated
     */
    public void setSumSalary(Double sumSalary) {
        this.sumSalary = sumSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.salary_month
     *
     * @return the value of salary.salary_month
     *
     * @mbggenerated
     */
    public String getSalaryMonth() {
        return salaryMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.salary_month
     *
     * @param salaryMonth the value for salary.salary_month
     *
     * @mbggenerated
     */
    public void setSalaryMonth(String salaryMonth) {
        this.salaryMonth = salaryMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.salary_status
     *
     * @return the value of salary.salary_status
     *
     * @mbggenerated
     */
    public Integer getSalaryStatus() {
        return salaryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.salary_status
     *
     * @param salaryStatus the value for salary.salary_status
     *
     * @mbggenerated
     */
    public void setSalaryStatus(Integer salaryStatus) {
        this.salaryStatus = salaryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.ext_a
     *
     * @return the value of salary.ext_a
     *
     * @mbggenerated
     */
    public String getExtA() {
        return extA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.ext_a
     *
     * @param extA the value for salary.ext_a
     *
     * @mbggenerated
     */
    public void setExtA(String extA) {
        this.extA = extA == null ? null : extA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.ext_b
     *
     * @return the value of salary.ext_b
     *
     * @mbggenerated
     */
    public String getExtB() {
        return extB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.ext_b
     *
     * @param extB the value for salary.ext_b
     *
     * @mbggenerated
     */
    public void setExtB(String extB) {
        this.extB = extB == null ? null : extB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.ext_c
     *
     * @return the value of salary.ext_c
     *
     * @mbggenerated
     */
    public String getExtC() {
        return extC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.ext_c
     *
     * @param extC the value for salary.ext_c
     *
     * @mbggenerated
     */
    public void setExtC(String extC) {
        this.extC = extC == null ? null : extC.trim();
    }

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Override
	public String toString() {
		return "Salary [salaryId=" + salaryId + ", empId=" + empId + ", baseSalary=" + baseSalary + ", achievements="
				+ achievements + ", bonus=" + bonus + ", checkDeduction=" + checkDeduction + ", sumSalary=" + sumSalary
				+ ", salaryMonth=" + salaryMonth + ", salaryStatus=" + salaryStatus + ", extA=" + extA + ", extB="
				+ extB + ", extC=" + extC + ", empName=" + empName + "]";
	}

    
}