package com.hr.dao;

import com.hr.bean.Achives;
import java.util.List;

public interface AchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achives
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achives
     *
     * @mbggenerated
     */
    int insert(Achives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achives
     *
     * @mbggenerated
     */
    Achives selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achives
     *
     * @mbggenerated
     */
    List<Achives> selectAll(Achives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achives
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Achives record);
    
    
    /**
     * 更新档案状态
     * @param record
     * @return
     */
    int updateAchivesStatus(Achives record);
}