package com.hr.dao;

import java.util.List;
import java.util.Map;

import com.hr.bean.Asessment;

public interface AsessmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asessment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer asessmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asessment
     *
     * @mbggenerated
     */
    int insert(Asessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asessment
     *
     * @mbggenerated
     */
    Asessment selectByPrimaryKey(Integer asessmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asessment
     *
     * @mbggenerated
     */
    List<Asessment> selectAll(Asessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asessment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Asessment record);
    
    /**
     * 更新状态
     * @param record
     * @return
     */
    int updateStatusByPoJo(Asessment record);
    
    
    /**
     * 查询当月考勤扣除金额
     * @param param
     * @return
     */
    double selectTotaMoneyByEmpId(Map<String,Object> param);
}