package com.hr.dao;

import com.hr.bean.Recruit;
import java.util.List;

public interface RecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recruitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    int insert(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    Recruit selectByPrimaryKey(Integer recruitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    List<Recruit> selectAll(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recruit record);
}