package com.hr.dao;

import com.hr.bean.Salary;
import java.util.List;

public interface SalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer salaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary
     *
     * @mbggenerated
     */
    int insert(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary
     *
     * @mbggenerated
     */
    Salary selectByPrimaryKey(Integer salaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary
     *
     * @mbggenerated
     */
    List<Salary> selectAll(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Salary record);
    
    /**
     * 检查本月是否已经创建过薪资单
     * @param record
     * @return
     */
    int selectCountByPoJo(Salary record);
    
}